// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApm2DBq0CnUogP_b_q1285HSJJGQEBc68',
    appId: '1:780438032468:web:72c7c143f1f997ee7b9dc1',
    messagingSenderId: '780438032468',
    projectId: 'nexgen-agri',
    authDomain: 'nexgen-agri.firebaseapp.com',
    storageBucket: 'nexgen-agri.appspot.com',
    measurementId: 'G-K0XE9RYJ9K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQG6ek4qAjX-bloX4LMSvqiAtYGrxc10o',
    appId: '1:780438032468:android:0550cc146c2e83c27b9dc1',
    messagingSenderId: '780438032468',
    projectId: 'nexgen-agri',
    storageBucket: 'nexgen-agri.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDNfAQxwU3944ouiWCv7FavuoTyeeRRlo',
    appId: '1:780438032468:ios:c65ffa7053ec28147b9dc1',
    messagingSenderId: '780438032468',
    projectId: 'nexgen-agri',
    storageBucket: 'nexgen-agri.appspot.com',
    iosBundleId: 'com.example.nexgenAgri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDNfAQxwU3944ouiWCv7FavuoTyeeRRlo',
    appId: '1:780438032468:ios:c65ffa7053ec28147b9dc1',
    messagingSenderId: '780438032468',
    projectId: 'nexgen-agri',
    storageBucket: 'nexgen-agri.appspot.com',
    iosBundleId: 'com.example.nexgenAgri',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApm2DBq0CnUogP_b_q1285HSJJGQEBc68',
    appId: '1:780438032468:web:63732fa0d73c8fc77b9dc1',
    messagingSenderId: '780438032468',
    projectId: 'nexgen-agri',
    authDomain: 'nexgen-agri.firebaseapp.com',
    storageBucket: 'nexgen-agri.appspot.com',
    measurementId: 'G-2PDMK4KGC9',
  );

}